server:
  port: ${GAME_SERVICE_PORT:7331}

spring:
  application:
    name: locke-game-service
  data:
    mongodb:
      uri: 'mongodb://${MONGO_HOST:host.docker.internal}:${MONGO_PORT:27017}/locke-db'

application:
  tournament:
    key: ${CHALLONGE_API_KEY}
    uri: 'https://api.challonge.com/v1/'