server:
  port: ${GAME_SERVICE_PORT:7331}

spring:
  application:
    name: locke-game-service
  data:
    mongodb:
      authentication-database: ${GAME_SERVICE_AUTHENTICATION_DB:locke-db}
      username: ${GAME_SERVICE_DB_USERNAME}
      password: ${GAME_SERVICE_DB_PASSWORD}
      database: ${GAME_SERVICE_DB_NAME:locke-db}
      port: ${GAME_SERVICE_DB_PORT:27017}
      host: ${GAME_SERVICE_DB_HOST:localhost}

application:
  tournament:
    key: ${CHALLONGE_API_KEY}
    uri: 'https://api.challonge.com/v1/'